[package]
name = "hearnotes"
version = "1.1.0"
description = "HearNotes local transcription and speaker separation"
authors = ["KonaLz"]
edition = "2021"
license = "MIT"
repository = "https://github.com/KonaLz/HearNotes"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
