[package]
name = "meeting-scribe"
version = "1.0.1"
description = "HearNotes local transcription and speaker separation"
authors = ["KonaLz"]
edition = "2021"
license = "MIT"
repository = "https://github.com/KonaLz/meeting-scribe-tauri"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"

[features]
custom-protocol = ["tauri/custom-protocol"]
